### ISSUE TITLE
Prefer using Gradle Wrapper when it is available

### ISSUE THREAD

**Issue by shanman190** [snyk/snyk-gradle-plugin#124]
Node: v12.16.3
NPM: 6.14.4
Snyk: 1.330.2

When scanning a Gradle project, if a `gradlew/gradlew.bat` is present it should be given preference over a system installation of Gradle. The gradle wrapper will ensure that the correct version of Gradle for the current project is downloaded if needed and then executed.

**Comment by anthogez** [comment]
HI @shanman190, thanks for raising this issue.
We solved it on snyk-gradle-plugin v3.3.4 and snyk-cli v1.330.4 :)
