### ISSUE TITLE
multi-module projects fail when using configuration-matching

### ISSUE THREAD

**Issue by akibabu** [snyk/snyk-gradle-plugin#192]
## Problem
Using this command
`snyk -d --all-sub-projects --configuration-matching=^runtimeClasspath$ test`

For example in a multi project like this where the `bom` module produces only a java-platform.
```
build.gradle               OK
some-code/build.gradle     OK
...                        OK
bom/build.gradle           <- Fails because there is no runtimeClasspath in this project

```

## Problem 2
Adding the `--exclude` option for the folder does not help. Same error is evaluated before it seems.

## Question
Can the option `configuration-matching` ignore projects that doesn't match?
That's my expectation from the name `matching`, acting as a filter, but maybe there are other factors at play.

Code that throws the error:
https://github.com/snyk/snyk-gradle-plugin/blob/9989b21137695bedc5182f551e6d3299e6eebb23/lib/init.gradle#L272-L276

**Comment by confusedcrib** [comment]
Thanks for reporting this, we seem to be having the same issue running without any `--configuration-matching` specified at all for a project that similarly only produces a java-platform with no code throwing the error `Matching configurations not found: .*`

We similarly need either a way to exclude the project, or for the tests to just pass by default.

**Comment by shanman190** [comment]
So from a Gradle standpoint, I would have expected for the default `--configuration-matching .*` to have worked on a `java-platform` project unless that project has errors. In a `java-platform` project it does have one resolveable configuration of dependencies named `classpath` and all other configurations are of the form `canBeResolved=false` and `canBeConsumed=false`.

Now for the original `--configuration-matching runtimeClasspath`, I would expect for this to fail as the configuration `runtimeClasspath` does not exist in a `java-platform` project.

Resources:
https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlatformPlugin.java#L120

**Comment by akibabu** [comment]
> I would expect for this to fail as the configuration runtimeClasspath does not exist in a java-platform project.

`java-platform` was just an example in this case. There are other projects where a sub-project could be used for anything, like tools or frontend builds.

I don't expect something called "matching" to fail, but instead select all subprojects matching and not the others.
Now instead of a `matcher` it's a `validator` that forces all sub-projects to be of some kind, this should not be a concern of Snyk.

Problem is there is no work-around as stated above `--exclude` doesn't work. Selecting a single sub-project with `--sub-project` relieves the problem, but that only works when there's a single project you need to scan.

**Comment by trevjonez** [comment]
seeing issues similar to this issue that I believe is a regression from this PR. Timing wise it lines up with when our jobs started to explode.
https://github.com/snyk/snyk-gradle-plugin/pull/222

Invocation to gradle is effectively this
```bash
DEBUG="foo" ./gradlew --init-script gradle/init.d/snyk.gradle -Pconfiguration=^prodReleaseRuntimeClasspath$ -PonlySubProject=app snykResolvedDepsJson --stacktrace
```

in a large multi project layout we see the snyk task that is injected via init script is running on every project now
```

> Task :cms:snykResolvedDepsJson FAILED
SNYKECHO snykResolvedDepsJson task is executing via doLast

> Task :analytics:snykResolvedDepsJson FAILED
SNYKECHO snykResolvedDepsJson task is executing via doLast

> Task :claims:snykResolvedDepsJson FAILED
SNYKECHO snykResolvedDepsJson task is executing via doLast

> Task :snykResolvedDepsJson FAILED
SNYKECHO snykResolvedDepsJson task is executing via doLast

> Task :benefitsComponents:snykResolvedDepsJson FAILED
SNYKECHO snykResolvedDepsJson task is executing via doLast

> Task :app:snykResolvedDepsJson FAILED
SNYKECHO snykResolvedDepsJson task is executing via doLast

> Task :appStartup:snykResolvedDepsJson FAILED
SNYKECHO snykResolvedDepsJson task is executing via doLast

> Task :benefitsMapper:snykResolvedDepsJson FAILED
SNYKECHO snykResolvedDepsJson task is executing via doLast
```

Given that we are instructing snyk to only run on a given configuration(s) on a single sub project we probably shouldn't even be creating all these tasks on the other sub projects.

Probably time to do some heavy rework to the init injection or go to a full gradle plugin if need to be so the overall setup can be configuration cache safe?

FYI: @magdziarek & @gitphill

**Comment by magdziarek** [comment]
@trevjonez thanks for flagging this up. We are looking into improving the init script, will keep you posted.

**Comment by ronanbrowne** [comment]
FYI this also effects our use case in some projects, example when i run 

` snyk test --all-sub-projects --configuration-matching='^runtimeClasspath$'`

on a project where the root does not have this configuration it falls over, despite been present in some submodules, Would be keen to see this resolved in future versions.
